### ISSUE TITLE
Not working with data-title-sha

### ISSUE THREAD

**Issue by dcorb** [btmills/geopattern#13]
![image](https://cloud.githubusercontent.com/assets/881333/8481004/ddbec0f4-20d8-11e5-988a-faad1a4f2497.png)

I got it working manually passing a new custom attribute
````
          $(this).geopattern($(this).attr('data-title-sha-custom'));

**Comment by btmills** [comment]
What was the value of `data-title-sha`? The library assumes it is a valid sha1 output, but it never verifies that, and I don't believe I documented it.

**Comment by dcorb** [comment]
I tried different values
Here is a reduced test case http://jsfiddle.net/L7qgdczu/

**Comment by btmills** [comment]
Aha! Thanks for that repro, it's perfect. The `data-title-sha` attribute comes from the original geopattern script for [GitHub Guides](https://guides.github.com/), when `data-title-sha` contained the sha1 hash of the title, for example:

```html
<h3 data-title-sha="e8df966767fbd3a383c53216799beb4b4564cb74">Mastering Markdown</h3>
```

Support for `data-title-sha` remains for backwards compatibility, but the library is primarily intended to be used by passing a string as the first argument, like you did by passing the value of your custom attribute. If you still want to use it with the `data-title-sha` attribute, replace its value with the sha1 hash of whatever string you want to use. For example, using "test" as the source string:

```html
<div data-title-sha="a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"></div>
```

Here's a [fork of your fiddle](http://jsfiddle.net/19rkshcq/) updated so that both divs work; all I did was replace "test" with its sha1 hash.

**Comment by dcorb** [comment]
Alright! 
Thanks for the explanation, of course it makes sense. 
I will close the issue
