### ISSUE TITLE
How can I edit this to support multiple colors?

### ISSUE THREAD

**Issue by koichirose** [btmills/geopattern#38]
I'd like to work on this to support at least two colors, not sure where to begin.
Anyone can point me in the right direction?

**Comment by btmills** [comment]
This library creates patterns by first [generating a solid color background](https://github.com/btmills/geopattern/blob/7f7fd7916fe13b9600b9d586d73a59541e4060dd/lib/pattern.js#L117-L142) and then overlaying [light or dark shapes of varying opacity](https://github.com/btmills/geopattern/blob/7f7fd7916fe13b9600b9d586d73a59541e4060dd/lib/pattern.js#L33-L38) on top of the background. I’d start with the shapes - maybe you’d be able to select a color for the overlays rather than just the hard-coded dark and light values? That could lead to an interesting plaid-like effect if you selected the colors carefully and thought about the blending modes.

Closing this issue since it’s not a code change or the repository to track, but I hope that was helpful. If you get it working, please throw a link to a demo of your fork in a comment so people can check it out!
