### ISSUE TITLE
Can't find variable: Buffer

### ISSUE THREAD

**Issue by bfarrgaynor** [btmills/geopattern#40]
I realize this is NOT a react-native component, however, when using this on react-native, it complains 'Buffer' isn't available when running generate(); 

It worked beautifully prior, but after I upgraded to a newer version of iOS, it broke on this specifically. Not sure if that matters or not, but you should list buffer as a dependency.

**Comment by bfarrgaynor** [comment]
For those that discover this....

I added 'buffer' to my project with 
```yarn add buffer```

Then in: node_modules/geopattern/lib/pattern.js

I added:

```
import { Buffer } from 'buffer';
```
To the top of the file after 'use strict'; which fixes the issue.

**Comment by toddmitchell** [comment]
> For those that discover this....
> 
> I added 'buffer' to my project with
> `yarn add buffer`
> 
> Then in: node_modules/geopattern/lib/pattern.js
> 
> I added:
> 
> ```
> import { Buffer } from 'buffer';
> ```
> 
> To the top of the file after 'use strict'; which fixes the issue.

Cheers.  Worked for me

**Comment by btmills** [comment]
> It worked beautifully prior, but after I upgraded to a newer version of iOS, it broke on this specifically.

That's curious. The code looks for either `window.btoa()` in the browser or `Buffer` in Node.js:

https://github.com/btmills/geopattern/blob/7f7fd7916fe13b9600b9d586d73a59541e4060dd/lib/pattern.js#L95-L107

Did a more recent version of iOS or React Native drop one of those APIs?

I'm not sure React Native even existed when this was written, but I'm open to supporting it. I'm reluctant to add `buffer` to `dependencies` since it's not needed in browsers or Node.js. If there's a built-in API for base64 encoding in React Native, that'd be ideal. Otherwise adding a docs note like in #33 could work.
